app = "datastar"
primary_region = "den"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_handlers]]
  action = "redirect"
  status_code = 301
  url = "https://data-star.dev"

[[vm]]
  memory = "512mb"